project:
  title: "Semester Research Project"

editor: visual
execute:
  echo: true
  cache: true
knitr:
  opts_chunk:
    echo: true
    cache: true
    cache.lazy: false

format:
  html:
    css: "css/grading.css"
